/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AdminStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'inProgress' : IDL.Null,
  'paused' : IDL.Null,
});
export const AgentApplication = IDL.Record({
  'id' : IDL.Nat,
  'age' : IDL.Nat,
  'status' : AdminStatus,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'lastUpdated' : IDL.Int,
  'email' : IDL.Text,
  'notes' : IDL.Text,
  'statusTimestamps' : IDL.Vec(IDL.Tuple(AdminStatus, IDL.Int)),
  'phone' : IDL.Text,
  'adminNotes' : IDL.Text,
  'location' : IDL.Text,
});
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'status' : AdminStatus,
  'policyInterest' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'lastUpdated' : IDL.Int,
  'submittedBy' : IDL.Principal,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'statusTimestamps' : IDL.Vec(IDL.Tuple(AdminStatus, IDL.Int)),
  'phone' : IDL.Text,
  'adminNotes' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminCreateAgentApplication' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        AdminStatus,
        IDL.Text,
      ],
      [AgentApplication],
      [],
    ),
  'adminCreateInquiry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        AdminStatus,
        IDL.Text,
        IDL.Principal,
      ],
      [Inquiry],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAgentApplication' : IDL.Func([IDL.Nat], [], []),
  'deleteInquiry' : IDL.Func([IDL.Nat], [], []),
  'getAll' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Bool)],
      [IDL.Vec(Inquiry)],
      [],
    ),
  'getAllAgentApplications' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Bool)],
      [IDL.Vec(AgentApplication)],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submit' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Inquiry],
      [],
    ),
  'submitAgentApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [AgentApplication],
      [],
    ),
  'updateAgentApplicationStatus' : IDL.Func(
      [IDL.Nat, AdminStatus, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateInquiryStatus' : IDL.Func(
      [IDL.Nat, AdminStatus, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AdminStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'inProgress' : IDL.Null,
    'paused' : IDL.Null,
  });
  const AgentApplication = IDL.Record({
    'id' : IDL.Nat,
    'age' : IDL.Nat,
    'status' : AdminStatus,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'lastUpdated' : IDL.Int,
    'email' : IDL.Text,
    'notes' : IDL.Text,
    'statusTimestamps' : IDL.Vec(IDL.Tuple(AdminStatus, IDL.Int)),
    'phone' : IDL.Text,
    'adminNotes' : IDL.Text,
    'location' : IDL.Text,
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'status' : AdminStatus,
    'policyInterest' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'lastUpdated' : IDL.Int,
    'submittedBy' : IDL.Principal,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'statusTimestamps' : IDL.Vec(IDL.Tuple(AdminStatus, IDL.Int)),
    'phone' : IDL.Text,
    'adminNotes' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminCreateAgentApplication' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          AdminStatus,
          IDL.Text,
        ],
        [AgentApplication],
        [],
      ),
    'adminCreateInquiry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          AdminStatus,
          IDL.Text,
          IDL.Principal,
        ],
        [Inquiry],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAgentApplication' : IDL.Func([IDL.Nat], [], []),
    'deleteInquiry' : IDL.Func([IDL.Nat], [], []),
    'getAll' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Bool)],
        [IDL.Vec(Inquiry)],
        [],
      ),
    'getAllAgentApplications' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Bool)],
        [IDL.Vec(AgentApplication)],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submit' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Inquiry],
        [],
      ),
    'submitAgentApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [AgentApplication],
        [],
      ),
    'updateAgentApplicationStatus' : IDL.Func(
        [IDL.Nat, AdminStatus, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateInquiryStatus' : IDL.Func(
        [IDL.Nat, AdminStatus, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };