/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AdminStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'inProgress' : null } |
  { 'paused' : null };
export interface AgentApplication {
  'id' : bigint,
  'age' : bigint,
  'status' : AdminStatus,
  'name' : string,
  'createdAt' : bigint,
  'lastUpdated' : bigint,
  'email' : string,
  'notes' : string,
  'statusTimestamps' : Array<[AdminStatus, bigint]>,
  'phone' : string,
  'adminNotes' : string,
  'location' : string,
}
export interface Inquiry {
  'id' : bigint,
  'status' : AdminStatus,
  'policyInterest' : string,
  'name' : string,
  'createdAt' : bigint,
  'lastUpdated' : bigint,
  'submittedBy' : Principal,
  'email' : string,
  'message' : string,
  'statusTimestamps' : Array<[AdminStatus, bigint]>,
  'phone' : string,
  'adminNotes' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminCreateAgentApplication' : ActorMethod<
    [string, string, string, bigint, string, string, AdminStatus, string],
    AgentApplication
  >,
  'adminCreateInquiry' : ActorMethod<
    [string, string, string, string, string, AdminStatus, string, Principal],
    Inquiry
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAgentApplication' : ActorMethod<[bigint], undefined>,
  'deleteInquiry' : ActorMethod<[bigint], undefined>,
  'getAll' : ActorMethod<[[] | [string], [] | [boolean]], Array<Inquiry>>,
  'getAllAgentApplications' : ActorMethod<
    [[] | [string], [] | [boolean]],
    Array<AgentApplication>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submit' : ActorMethod<[string, string, string, string, string], Inquiry>,
  'submitAgentApplication' : ActorMethod<
    [string, string, string, bigint, string, string],
    AgentApplication
  >,
  'updateAgentApplicationStatus' : ActorMethod<
    [bigint, AdminStatus, [] | [string]],
    undefined
  >,
  'updateInquiryStatus' : ActorMethod<
    [bigint, AdminStatus, [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];