/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AgentApplication {
    id: bigint;
    age: bigint;
    status: AdminStatus;
    name: string;
    createdAt: bigint;
    lastUpdated: bigint;
    email: string;
    notes: string;
    statusTimestamps: Array<[AdminStatus, bigint]>;
    phone: string;
    adminNotes: string;
    location: string;
}
export interface Inquiry {
    id: bigint;
    status: AdminStatus;
    policyInterest: string;
    name: string;
    createdAt: bigint;
    lastUpdated: bigint;
    submittedBy: Principal;
    email: string;
    message: string;
    statusTimestamps: Array<[AdminStatus, bigint]>;
    phone: string;
    adminNotes: string;
}
export interface UserProfile {
    name: string;
}
export enum AdminStatus {
    pending = "pending",
    completed = "completed",
    approved = "approved",
    rejected = "rejected",
    inProgress = "inProgress",
    paused = "paused"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    adminCreateAgentApplication(name: string, phone: string, email: string, age: bigint, location: string, notes: string, status: AdminStatus, adminNotes: string): Promise<AgentApplication>;
    adminCreateInquiry(name: string, phone: string, email: string, policyInterest: string, message: string, status: AdminStatus, adminNotes: string, submittedBy: Principal): Promise<Inquiry>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteAgentApplication(applicationId: bigint): Promise<void>;
    deleteInquiry(inquiryId: bigint): Promise<void>;
    getAll(sort: string | null, reverse: boolean | null): Promise<Array<Inquiry>>;
    getAllAgentApplications(sort: string | null, reverse: boolean | null): Promise<Array<AgentApplication>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMyInquiries(): Promise<Array<Inquiry>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submit(name: string, phone: string, email: string, policyInterest: string, message: string): Promise<Inquiry>;
    submitAgentApplication(name: string, phone: string, email: string, age: bigint, location: string, notes: string): Promise<AgentApplication>;
    updateAgentApplicationStatus(applicationId: bigint, newStatus: AdminStatus, notes: string | null): Promise<void>;
    updateInquiryStatus(inquiryId: bigint, newStatus: AdminStatus, notes: string | null): Promise<void>;
}
import type { AdminStatus as _AdminStatus, AgentApplication as _AgentApplication, Inquiry as _Inquiry, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async adminCreateAgentApplication(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: string, arg6: AdminStatus, arg7: string): Promise<AgentApplication> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateAgentApplication(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_AdminStatus_n1(this._uploadFile, this._downloadFile, arg6), arg7);
                return from_candid_AgentApplication_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateAgentApplication(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_AdminStatus_n1(this._uploadFile, this._downloadFile, arg6), arg7);
            return from_candid_AgentApplication_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminCreateInquiry(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: AdminStatus, arg6: string, arg7: Principal): Promise<Inquiry> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateInquiry(arg0, arg1, arg2, arg3, arg4, to_candid_AdminStatus_n1(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
                return from_candid_Inquiry_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateInquiry(arg0, arg1, arg2, arg3, arg4, to_candid_AdminStatus_n1(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
            return from_candid_Inquiry_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteAgentApplication(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAgentApplication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAgentApplication(arg0);
            return result;
        }
    }
    async deleteInquiry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInquiry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInquiry(arg0);
            return result;
        }
    }
    async getAll(arg0: string | null, arg1: boolean | null): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAll(to_candid_opt_n13(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAll(to_candid_opt_n13(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAgentApplications(arg0: string | null, arg1: boolean | null): Promise<Array<AgentApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAgentApplications(to_candid_opt_n13(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAgentApplications(to_candid_opt_n13(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyInquiries(): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyInquiries();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyInquiries();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submit(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<Inquiry> {
        if (this.processError) {
            try {
                const result = await this.actor.submit(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Inquiry_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submit(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Inquiry_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitAgentApplication(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: string): Promise<AgentApplication> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAgentApplication(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_AgentApplication_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAgentApplication(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_AgentApplication_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAgentApplicationStatus(arg0: bigint, arg1: AdminStatus, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAgentApplicationStatus(arg0, to_candid_AdminStatus_n1(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAgentApplicationStatus(arg0, to_candid_AdminStatus_n1(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateInquiryStatus(arg0: bigint, arg1: AdminStatus, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInquiryStatus(arg0, to_candid_AdminStatus_n1(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInquiryStatus(arg0, to_candid_AdminStatus_n1(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n13(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_AdminStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminStatus): AdminStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_AgentApplication_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AgentApplication): AgentApplication {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Inquiry_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Inquiry): Inquiry {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _AdminStatus;
    policyInterest: string;
    name: string;
    createdAt: bigint;
    lastUpdated: bigint;
    submittedBy: Principal;
    email: string;
    message: string;
    statusTimestamps: Array<[_AdminStatus, bigint]>;
    phone: string;
    adminNotes: string;
}): {
    id: bigint;
    status: AdminStatus;
    policyInterest: string;
    name: string;
    createdAt: bigint;
    lastUpdated: bigint;
    submittedBy: Principal;
    email: string;
    message: string;
    statusTimestamps: Array<[AdminStatus, bigint]>;
    phone: string;
    adminNotes: string;
} {
    return {
        id: value.id,
        status: from_candid_AdminStatus_n5(_uploadFile, _downloadFile, value.status),
        policyInterest: value.policyInterest,
        name: value.name,
        createdAt: value.createdAt,
        lastUpdated: value.lastUpdated,
        submittedBy: value.submittedBy,
        email: value.email,
        message: value.message,
        statusTimestamps: from_candid_vec_n7(_uploadFile, _downloadFile, value.statusTimestamps),
        phone: value.phone,
        adminNotes: value.adminNotes
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    age: bigint;
    status: _AdminStatus;
    name: string;
    createdAt: bigint;
    lastUpdated: bigint;
    email: string;
    notes: string;
    statusTimestamps: Array<[_AdminStatus, bigint]>;
    phone: string;
    adminNotes: string;
    location: string;
}): {
    id: bigint;
    age: bigint;
    status: AdminStatus;
    name: string;
    createdAt: bigint;
    lastUpdated: bigint;
    email: string;
    notes: string;
    statusTimestamps: Array<[AdminStatus, bigint]>;
    phone: string;
    adminNotes: string;
    location: string;
} {
    return {
        id: value.id,
        age: value.age,
        status: from_candid_AdminStatus_n5(_uploadFile, _downloadFile, value.status),
        name: value.name,
        createdAt: value.createdAt,
        lastUpdated: value.lastUpdated,
        email: value.email,
        notes: value.notes,
        statusTimestamps: from_candid_vec_n7(_uploadFile, _downloadFile, value.statusTimestamps),
        phone: value.phone,
        adminNotes: value.adminNotes,
        location: value.location
    };
}
function from_candid_tuple_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_AdminStatus, bigint]): [AdminStatus, bigint] {
    return [
        from_candid_AdminStatus_n5(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    approved: null;
} | {
    rejected: null;
} | {
    inProgress: null;
} | {
    paused: null;
}): AdminStatus {
    return "pending" in value ? AdminStatus.pending : "completed" in value ? AdminStatus.completed : "approved" in value ? AdminStatus.approved : "rejected" in value ? AdminStatus.rejected : "inProgress" in value ? AdminStatus.inProgress : "paused" in value ? AdminStatus.paused : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Inquiry>): Array<Inquiry> {
    return value.map((x)=>from_candid_Inquiry_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AgentApplication>): Array<AgentApplication> {
    return value.map((x)=>from_candid_AgentApplication_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_AdminStatus, bigint]>): Array<[AdminStatus, bigint]> {
    return value.map((x)=>from_candid_tuple_n8(_uploadFile, _downloadFile, x));
}
function to_candid_AdminStatus_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdminStatus): _AdminStatus {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: boolean | null): [] | [boolean] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdminStatus): {
    pending: null;
} | {
    completed: null;
} | {
    approved: null;
} | {
    rejected: null;
} | {
    inProgress: null;
} | {
    paused: null;
} {
    return value == AdminStatus.pending ? {
        pending: null
    } : value == AdminStatus.completed ? {
        completed: null
    } : value == AdminStatus.approved ? {
        approved: null
    } : value == AdminStatus.rejected ? {
        rejected: null
    } : value == AdminStatus.inProgress ? {
        inProgress: null
    } : value == AdminStatus.paused ? {
        paused: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
